brands/urls.py
from django.urls import path
from . import views


app_name = 'brands'

urlpatterns = [
    path('create/brand/', views.create_brand, name='brand_create'),
]

catalogs/urls.py
from django.urls import path
from . import views


app_name = 'catalogs'

urlpatterns = [
    path('create/category/', views.create_category, name='category_create'),
]

colors/urls.py
from django.urls import path
from . import views


app_name = 'color'

urlpatterns = [
    path('create/color/', views.create_color, name='create_color'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('products/', include('products.urls')),
    path('brands/', include('brands.urls')),
    path('catalogs/', include('catalogs.urls')),
    path('colors/', include('colors.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('list/', views.product_list, name='list'),
    path('create/product', views.create_product, name='product_create'),
    path('success/review/<int:pk>/', views.success_review, name='success_review'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.product_detail, name='detail'),
]

templates/includes/footer.html
<footer class="animate-fade-in">
    <p>&copy; 2023 Astrum Market. All rights reserved.</p>
</footer>

templates/includes/header.html
<header class="animate-fade-in">
    <div class="header-content">
        <a href="/" class="logo">Astrum Market</a>
        <nav>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'products:list' %}">Products</a>
            <a href="{% url 'products:product_create' %}">Add Product</a>
            <a href="{% url 'brands:brand_create' %}">Add Brand</a>
            <a href="{% url 'catalogs:category_create' %}">Add Category</a>
            <a href="{% url 'color:create_color' %}">Add Color</a>
        </nav>
    </div>
</header>